version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    assignees:
      - "sleberknight"
      - "chrisrohr"
    reviewers:
      - "sleberknight"
      - "chrisrohr"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
    assignees:
      - "sleberknight"
      - "chrisrohr"
    reviewers:
      - "sleberknight"
      - "chrisrohr"
